name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      description: Select the component where you encountered the bug
      options:
        - Album Viewer (Vue.js Frontend)
        - Album API v2 (Node.js)
        - Album API (.NET)
        - Infrastructure/DevOps
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what should have happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: If applicable, what version of Node.js are you using?
      placeholder: "e.g., 18.17.0"

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: If applicable, what version of .NET are you using?
      placeholder: "e.g., 8.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue
